### ISSUE TITLE
Sec 6.3.3 Lazy evaluation code

### ISSUE THREAD

**Issue by cherkis** [phagenlocher/learn-haskell-by-example#3]
The code (on page 126 of printed book) corresponds to
const 1000^100000000 0 
and would take time, 
while in the following text 
const 0 100^100000000
is discussed instead.
x and y values in the code should be interchanged.

**Comment by phagenlocher** [comment]
Good catch, thank you for spotting this! 

To keep a better overview for a later revision, it would be extremely helpful if you could add your finding to the liveBook discussion: https://livebook.manning.com/forum?product=hagenlocher&page=1

Thanks!
